file: Prelab10.o Prelab_10.o
	gcc  Prelab10.o Prelab_10.o -o file
Prelab10.o: Prelab1 Prelab10.o Prelab_10.o -o file
	gcc -c Prelab10.c
main.o: Prelab10.h Prelab_10.h main.c
	gcc -c main.c
Prelab_10: Prelab_10.h Prelab_10.c
	gcc -c Prelab_10.c



